# Generated by Django 5.1.4 on 2024-12-18 20:01

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_content_alter_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('slider', 'Slider'), ('banner', 'Banner'), ('snackbar', 'Snackbar')], default='text', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.CreateModel(
            name='BannerBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField()),
            ],
            bases=('page.block',),
        ),
        migrations.CreateModel(
            name='ImageTextButtonsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='image_text_blocks/')),
                ('button_text_1', models.CharField(max_length=50)),
                ('button_url_1', models.URLField()),
                ('button_text_2', models.CharField(max_length=50)),
                ('button_url_2', models.URLField()),
            ],
            bases=('page.block',),
        ),
        migrations.CreateModel(
            name='SnackbarBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
                ('message', models.TextField()),
                ('action_text', models.CharField(max_length=100)),
                ('action_url', models.URLField()),
            ],
            bases=('page.block',),
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.block')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='blocks',
            field=models.ManyToManyField(related_name='pages', through='page.PageBlock', to='page.block'),
        ),
        migrations.CreateModel(
            name='SliderBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
                ('images', models.ManyToManyField(related_name='sliders', to='page.sliderimage')),
            ],
            bases=('page.block',),
        ),
    ]
