# Generated by Django 5.1.4 on 2024-12-20 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('page', '0003_block_sliderimage_alter_page_content_bannerblock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='imagetextbuttonsblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sliderblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='snackbarblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='block',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('slider', 'Slider'), ('banner', 'Banner'), ('snackbar', 'Snackbar'), ('slider_image', 'Slider Image'), ('image_text_buttons', 'Image Text Buttons')], default='text', max_length=20),
        ),
    ]
