# Generated by Django 5.1.4 on 2024-12-20 17:19

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_bannerblock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('page.block',),
        ),
        migrations.CreateModel(
            name='QuoteBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.block')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('page.block',),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagetextbuttonsblock',
            name='block_ptr',
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='images',
        ),
        migrations.RemoveField(
            model_name='snackbarblock',
            name='block_ptr',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('my_order',)},
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='visibility',
        ),
        migrations.AddField(
            model_name='block',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(default='Block', max_length=100),
        ),
        migrations.AddField(
            model_name='block',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='sliderblock',
            name='autoplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sliderblock',
            name='loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sliderblock',
            name='slider_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_pages', to='page.block'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='page.page'),
        ),
        migrations.CreateModel(
            name='BlockElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('title', 'Title'), ('image', 'Image'), ('text', 'Text'), ('button', 'Button')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('rich_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='page.block')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blocks/slider/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_items', to='page.sliderblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='BannerBlock',
        ),
        migrations.DeleteModel(
            name='ImageTextButtonsBlock',
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
        migrations.DeleteModel(
            name='SnackbarBlock',
        ),
    ]
