# Generated by Django 5.1.4 on 2024-12-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_complexblock_quoteblock_quoteitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexblock',
            options={'ordering': ['order'], 'verbose_name': 'Complex Block', 'verbose_name_plural': 'Complex Blocks'},
        ),
    ]
