# Generated by Django 5.1.4 on 2024-12-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_complexblock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderblock',
            name='slider_name',
            field=models.CharField(default='Slider', max_length=100),
        ),
    ]
