# Generated by Django 5.1.4 on 2024-12-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_sliderblock_slider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexblock',
            options={'verbose_name': 'Complex Block', 'verbose_name_plural': 'Complex Blocks'},
        ),
        migrations.RemoveField(
            model_name='sliderblock',
            name='slider_name',
        ),
    ]
