# Generated by Django 5.1.4 on 2024-12-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_complexblock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='slideritem',
            options={},
        ),
        migrations.RemoveField(
            model_name='slideritem',
            name='order',
        ),
    ]
