# Generated by Django 5.1.4 on 2024-12-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_complexblock_options_alter_slideritem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
