# Generated by Django 5.1.4 on 2024-12-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_slideritem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ['order']},
        ),
    ]
