# Generated by Django 5.1.4 on 2024-12-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_slideritem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockelement',
            options={},
        ),
        migrations.RemoveField(
            model_name='blockelement',
            name='order',
        ),
    ]
