# Generated by Django 5.1.4 on 2024-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_blockelement_options_remove_blockelement_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockelement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
