# Generated by Django 5.1.4 on 2024-12-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_blockelement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockelement',
            name='order',
        ),
    ]
