# Generated by Django 5.1.4 on 2024-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_remove_blockelement_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockelement',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blockelement',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
